apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ghcr.io/mechgit0/react-app:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-secret

